#!/usr/bin/env bash
# install and  Configure ufw to block all incoming traffic
# except for the following ports: 22, 443 and 80. 

sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable -y
